#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 현재 브랜치 이름 가져오기
branch="$(git rev-parse --abbrev-ref HEAD)"

# main 브랜치로의 push를 방지
if [ "$branch" = "main" ]; then
  echo "main 브랜치에 직접 push할 수 없습니다. 다른 브랜치를 사용하세요."
  exit 1
fi

exit 0